In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [5]:
df = pd.read_csv('/content/drive/MyDrive/ANN/Churn_Modelling.csv')
df.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [7]:
tf.__version__

'2.15.0'

In [8]:
dataset = pd.read_csv('/content/drive/MyDrive/ANN/Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values


In [9]:
print(X), print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


(None, None)

In [10]:
dataset['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

## Encoding The categorical data

In [13]:
# Label Encoding Gender Label
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X[:,2] = le.fit_transform(X[:,2])

In [17]:
print(X)# Female - 0 ad Male - 1

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One Hot Encoding 'geography' column

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset into the Training Set and Test Set

In [21]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

## Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

##Building The ANN
* Initializing the ANN
* Adding the input layer and first hidden layer
* Adding the second hidden layer
* Adding the output layer

In [24]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [25]:
# Adding the input layer and first hidden layer    # Activation func - rectifier(relu)
ann.add(tf.keras.layers.Dense(units =6,activation = 'relu'))

In [26]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units =6,activation = 'relu'))

In [27]:
# Adding the output layer    # Activation func - sigmoid()
ann.add(tf.keras.layers.Dense(units=1,activation = 'sigmoid'))

## Training the ANN

# Compiling The ANN

In [29]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

# Training the ANN on training set

In [30]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5702 - accuracy: 0.7502
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4762 - accuracy: 0.7955
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4490 - accuracy: 0.7950
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4379 - accuracy: 0.7977
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4319 - accuracy: 0.7995
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4270 - accuracy: 0.8023
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4219 - accuracy: 0.8064
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4154 - accuracy: 0.8125
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8242
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3930 - accura

## Making the Predictions and evaluating the model

In [ ]:
# Predicting the result of single observation
Use the ANN model to predict if the customer with the following info will leave the bank:
Geography : France
Credit Score : 600
Gender : Male
Age : 40 yrs old
Tenure : 3 Years
Balance : $ 60000
Number of Products : 2
Does this customer have a credit card? Yes
Is this customer an ActiveMember : Yes
Estimated Salary: $50000
So, should we say goodbye to that customer?

In [ ]:
# Note 1 : Notice that the values of the features were all the input in a doube pair of square brackets.
# that's because the 'predict' method always expects a 2D array as the format of its inputs. And putting our values
# into a double pair of square brackets makes the input exactly a 2D array

# Note 2 : Notice also that the France country was not input as string in the last column but as '1 0 0' n the first three
# Columns . Because of course the predict method expects the one hot encoded value of the state and we see in the first row
# Of the matrix of features X, "France" encoded as '1,0,0' and we need to take care of fummy variables

In [42]:
# Make a prediction
prediction = ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))
print(prediction[0]*100)

1/1 [==============================] - 0s 21ms/step
[2.4357247]


In [38]:
ann.evaluate(X_test,y_test)

63/63 [==============================] - 0s 4ms/step - loss: 0.3331 - accuracy: 0.8680


[0.3330819606781006, 0.8679999709129333]

In [39]:
print(ann.predict(X_test))

63/63 [==============================] - 0s 4ms/step
[[0.27279708]
 [0.37501723]
 [0.13049439]
 ...
 [0.0596757 ]
 [0.09850159]
 [0.15376137]]


In [43]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [44]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)



[[1526   69]
 [ 195  210]]


0.868