In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/ANN/heart.csv')
dataset.head(6)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   
5   39   M           NAP        120          339          0     Normal    170   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0  
5              N      0.0       Up             0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [10]:
dataset[:].isna().value_counts()

Age    Sex    ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease
False  False  False          False      False        False      False       False  False           False    False     False           918
Name: count, dtype: int64

In [11]:
dataset['ChestPainType'].value_counts()

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

In [13]:
dataset['RestingECG'].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [14]:
dataset['ST_Slope'].value_counts()

ST_Slope
Flat    460
Up      395
Down     63
Name: count, dtype: int64

In [15]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(X),print(y)

[[40 'M' 'ATA' ... 'N' 0.0 'Up']
 [49 'F' 'NAP' ... 'N' 1.0 'Flat']
 [37 'M' 'ATA' ... 'N' 0.0 'Up']
 ...
 [57 'M' 'ASY' ... 'Y' 1.2 'Flat']
 [57 'F' 'ATA' ... 'N' 0.0 'Flat']
 [38 'M' 'NAP' ... 'N' 0.0 'Up']]
[0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1
 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0
 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0
 1 0 0 0 1 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 0 0
 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1
 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 0 0 0 0
 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

(None, None)

In [17]:
# LAbel Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])
X[:,8] = le.fit_transform(X[:,8])
print(X)

[[40 1 'ATA' ... 0 0.0 'Up']
 [49 0 'NAP' ... 0 1.0 'Flat']
 [37 1 'ATA' ... 0 0.0 'Up']
 ...
 [57 1 'ASY' ... 1 1.2 'Flat']
 [57 0 'ATA' ... 0 0.0 'Flat']
 [38 1 'NAP' ... 0 0.0 'Up']]


In [18]:
# Categorical Encoding using OneHotEncoder

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columns_to_encode = [2,6,10]
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), columns_to_encode)
    ],
    remainder='passthrough'
)
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 172 0 0.0]
 [0.0 0.0 1.0 ... 156 0 1.0]
 [0.0 1.0 0.0 ... 98 0 0.0]
 ...
 [1.0 0.0 0.0 ... 115 1 1.2]
 [0.0 1.0 0.0 ... 174 0 0.0]
 [0.0 0.0 1.0 ... 173 0 0.0]]


In [19]:
print(X[:2])

[[0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 40 1 140 289 0 172 0 0.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 49 0 160 180 0 156 0 1.0]]


In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)


In [21]:
## Feature Scaling
from sklearn.preprocessing import StandardScaler
se = StandardScaler()
X_train = se.fit_transform(X_train)
X_test = se.fit_transform(X_test)


In [29]:
## Build an ANN model
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 10,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 10,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))


In [30]:
## Compiling the ANN Model
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])


In [31]:
## Training the model
ann.fit(X_train,y_train, batch_size = 32,epochs = 100)

Epoch 1/100
23/23 [==============================] - 1s 3ms/step - loss: 0.6415 - accuracy: 0.5899
Epoch 2/100
23/23 [==============================] - 0s 3ms/step - loss: 0.5780 - accuracy: 0.7030
Epoch 3/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5288 - accuracy: 0.7766
Epoch 4/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4872 - accuracy: 0.8038
Epoch 5/100
23/23 [==============================] - 0s 4ms/step - loss: 0.4504 - accuracy: 0.8215
Epoch 6/100
23/23 [==============================] - 0s 4ms/step - loss: 0.4206 - accuracy: 0.8392
Epoch 7/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3953 - accuracy: 0.8542
Epoch 8/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8665
Epoch 9/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3622 - accuracy: 0.8760
Epoch 10/100
23/23 [==============================] - 0s 2ms/step - loss: 0.3524 - accuracy: 0.8760
Epoch 11/

In [32]:
ann.evaluate(X_test,y_test)

6/6 [==============================] - 1s 8ms/step - loss: 0.4641 - accuracy: 0.8696


[0.4641367793083191, 0.8695651888847351]

In [34]:
print(ann.predict(X_test))

6/6 [==============================] - 0s 3ms/step
[[9.97438252e-01]
 [3.20712537e-01]
 [9.99523222e-01]
 [8.70021760e-01]
 [8.71613473e-02]
 [4.17096615e-02]
 [8.93020944e-04]
 [1.33283914e-03]
 [1.04910312e-02]
 [1.65649410e-02]
 [9.84065115e-01]
 [8.48096490e-01]
 [9.98368204e-01]
 [9.84383702e-01]
 [3.71798277e-02]
 [9.53236461e-01]
 [8.82765830e-01]
 [9.96407568e-01]
 [9.33258057e-01]
 [1.20399579e-01]
 [9.68806207e-01]
 [9.93217885e-01]
 [9.83538270e-01]
 [9.04003143e-01]
 [1.09481986e-03]
 [1.12481161e-04]
 [8.47712636e-01]
 [9.80351210e-01]
 [9.92412269e-01]
 [3.79290998e-01]
 [9.18850422e-01]
 [1.18299422e-03]
 [4.67757806e-02]
 [2.17409199e-03]
 [8.77748489e-01]
 [4.26185317e-03]
 [9.29141045e-01]
 [1.19171687e-03]
 [9.39318419e-01]
 [9.20708699e-04]
 [9.78584983e-04]
 [9.91768062e-01]
 [9.83750761e-01]
 [1.38234556e-01]
 [9.54644442e-01]
 [6.39763474e-03]
 [7.26821745e-05]
 [9.78987098e-01]
 [8.56405124e-02]
 [6.21814106e-04]
 [8.49521995e-01]
 [1.31086437e-02]
 [1.29631115e

In [35]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


6/6 [==============================] - 0s 5ms/step
[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 

In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)




[[64 13]
 [11 96]]


In [37]:
print(accuracy_score(y_test,y_pred))

0.8695652173913043


In [ ]:
## Predict Single Observation
Age: 26
Sex : M
ChestPAinType : ATA
REstingBP : 160
Cholesterol : 300
FastingBS : 0
REstingECG : Normal
MaxHR:156
ExceriseAngina:Y
OldPeak : 1
ST_Slope : Up
predict whether this patient has heart diease or not


In [40]:
print(ann.predict(se.transform([[26,1,0,1,0,0,160,300,0,0,1,0,156,1,1,0,0,1]])))

1/1 [==============================] - 0s 70ms/step
[[1.]]
